---
title: "Times Series Analysis"
author: 
- "Pablo E. Guti&eacute;rrez-Fonseca"
- "`r format(Sys.time(), '%d %B, %Y')`"
layout: default
permalink:
output: html_document
---
<br/>
<br/>


#### **Step 1**
Load libraries.<br>
```{r, warning=FALSE, message=FALSE}
libraries <- c('Kendall', 'trend')
lapply(libraries, require, character.only = TRUE)
```

<br/>

#### **Step 2**
```{r, warning=FALSE, message=FALSE}
rain <- read.csv("D:/OneDrive - University of Vermont/Curriculum/19_ Personal webpage/TropicalFreshwaterEcology/_pages/Lectures/data/StreamEcology_TS_precipitation.csv")
rainEVFS <- rain[,3] # Select colunm 3.  
```

<br/>

#### **Step 3**
```{r, warning=FALSE, message=FALSE}
rain.ts <- ts(rainEVFS, # Convert "Precipitation" to a time series object.
                    frequency=12, start=c(1975,1), end=c(2016,12))
head(rain.ts, n=24) 
```

<br/>

#### **Step 4**
```{r, warning=FALSE, message=FALSE}
plot(rain.ts, main="Precipitation El Verde")
```

<br/>

#### **Step 4**
We can use the Mann-Kendall Trend Test to see if there is a pattern in the data.
```{r, warning=FALSE, message=FALSE}
MannKendall(rain.ts)
# tau is a measure of the strength of the trend
# p-value for trend is also shown
```


<br/>
<br/>
