---
layout: default
title: "Publications"
permalink: /assignments/Publications/
---
</div>
</div>
<div class="container">
       
       
<h5><strong>2020</strong></h5>

<p><strong>Gutierrez-Fonseca, P.E.</strong>, Ramirez, A., Pringle, C.M., Torres, P.J., Crowl, T., Covich, A., Pérez, O. & W.H., McDowell. 2020.  When the rainforest dries up: drought effects on a tropical rainforest stream in Puerto Rico. Freshwater Sciences. [PDF](https://www.journals.uchicago.edu/doi/pdfplus/10.1086/708808)</p>
</div>

<h5><strong>2019</strong></h5>

<p>Classen-Rodriguez, L., <strong>Gutierrez-Fonseca, P.E.<strong> & A., Ramirez. 2019. Leaf-litter decomposition and macroinvertebrate assemblages along an urban stream gradient in Puerto Rico. Biotropica, 51, 641-651. [PDF](https://onlinelibrary.wiley.com/doi/full/10.1111/btp.12685?casa_token=SxRbcSedCnYAAAAA%3Ag-Xbuq6QzhwjpqJoNTLVGi9x9fpHaZnSbnGFXbBwWufOB9gATSKh7KJcAbfF3MyFZPoMvUh--5JAoMjd7w)</p>
</div>

<p>Bravo, F., Romero, D., <strong>Gutierrez-Fonseca, P.E.</strong> & S., Echeverria-Saenz. 2019. The description of Anacroneuria suerre sp. nov. from Costa Rica (Plecoptera: Perlidae) and using nymphs in ecotoxicological studies. Zootaxa, 4608(2), 357-364. [PDF](https://www.biotaxa.org/Zootaxa/article/view/zootaxa.4608.2.9)</p>
</div>

<p>Wohl, E., Hinshaw, S.K., Scamardo, J.E., & <strong>P.E. Gutiérrez-Fonseca</strong>. 2019. Transient Organic Jams in Puerto Rican Mountain Streams After Hurricanes. River Research and Applications, 35:280-289. [PDF](https://onlinelibrary.wiley.com/doi/full/10.1002/rra.3405)</p>
</div>

#### __2018__

Ramirez, A., ***Gutiérrez-Fonseca, P.E.***, Kelly, S. P., Engman, A.C., Wagner, K., Rosas, K.G., & Rodriguez, N. 2018. Drought facilitates species invasions in urban streams: Results from a long-term study of tropical island fish assemblage structure. Frontiers in Ecology and Evolution, 6, 115.  [PDF](https://www.frontiersin.org/articles/10.3389/fevo.2018.00115/full?&utm_source=Email_to_authors_&utm_medium=Email&utm_content=T1_11.5e1_author&utm_campaign=Email_publication&field=&journalName=Frontiers_in_Ecology_and_Evolution&id=324301)  

***Gutiérrez-Fonseca, P.E.***, Ramirez, A., & Pringle, C.M. 2018. Large-scale climatic phenomena drive fluctuations in macroinvertebrate assemblages in lowland tropical streams, Costa Rica: The importance of ENSO events in determining long-term (15y) patterns. PLoS One, 13(2), e0191781.  [PDF](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0191781)
<br>
<br>

#### __2017__

Cespedes, A. M. F., ***Gutiérrez-Fonseca, P.E.***, & Ramirez, A. 2017. Facilitacion entre Camarones y Efemeropteros en ecosistemas de arroyos de montana, Puerto Rico. Revista de la Asociación Colombiana de Ciencias Biológicas, 1(29), 15-20. [PDF](https://revistaaccb.org/r/index.php/accb/article/view/136)
<br>
<br>

#### __2016__

Klem, C.C. & ***P.E., Gutiérrez-Fonseca***. 2016. CO2-driven experimental acidification effects on aquatic macroinvertebrates in a tropical stream.  Journal of Freshwater Ecology, 32(1), 195-204. [PDF](https://www.tandfonline.com/doi/full/10.1080/02705060.2016.1259126)

Cornejo, A. & ***P.E., Gutiérrez-Fonseca***. 2016. Orden Plecoptera (Insecta) en Panama: Listado y distribucion de especies, comparacion con la riqueza taxonomica regional.  Puente Biologico, 7, 109-129. [PDF](https://www.researchgate.net/publication/303137423_Orden_Plecoptera_Insecta_en_Panama_listado_distribucion_de_especies_comparacion_con_la_riqueza_taxonomica_regional) 

Ramirez, A., & ***P.E., Gutiérrez-Fonseca***. 2016. Sobre ensambles y ensamblajes ecologicos-respuesta a Monge-Najera. Revista de Biológia Tropical, 64(2), 817-819. [PDF](https://www.redalyc.org/pdf/449/44945722028.pdf)


***Gutiérrez-Fonseca, P.E.***, & A., Ramirez. 2016. Evaluación de la calidad ecológica de los rios en Puerto Rico: principales amenazas y herramientas de evaluacion. Hidrobiologica, 26(3), 433-441.  [PDF](http://www.scielo.org.mx/scielo.php?pid=S0188-88972016000300433&script=sci_arttext&tlng=en)
<br>
<br>

#### __2015__

***Gutiérrez-Fonseca, P.E.***, P. E., & M., Springer. 2015. A new species of Anacroneuria Klapalek 1909 (Plecoptera: Perlidae) and notes on the altitudinal distribution of the genus in Costa Rica. Zootaxa, 4058(4), 595-600. [PDF](https://cecb7f23-7089-45fb-b01c-28fecf16b375.filesusr.com/ugd/9d5d38_95160e47778247fb87c399116098129b.pdf)


***Gutiérrez-Fonseca, P.E.***, A. M. Alonso-Rodriguez, A. Cornejo, A. C. Bailey, J. M. Maes & A. Ramirez. 2015. New records of Anacroneuria Klapalek, 1909 (Plecoptera: Perlidae) for Central America. Zootaxa, 3994(3), 445-448. [PDF](https://cecb7f23-7089-45fb-b01c-28fecf16b375.filesusr.com/ugd/9d5d38_55980cc178a0460693b0e131eda7faf7.pdf)


***Gutiérrez-Fonseca, P.E.***. 2015. Three new species of Anacroneuria Klapalek (Plecoptera: Perlidae) from Panama. Zootaxa, 3957(1), 69-76. [PDF](https://cecb7f23-7089-45fb-b01c-28fecf16b375.filesusr.com/ugd/9d5d38_daf4e7701e9a4e7e978657531d5b8486.pdf)
<br>
<br>

#### __2014__

Ramirez, A. & ***P.E., Gutiérrez-Fonseca***. Estudios sobre macroinvertebrados acuaticos en America Latina: avances recientes y direcciones futuras. Revista de Biologia Tropical. 62(Suppl2):9-20. [PDF](https://www.scielo.sa.cr/scielo.php?script=sci_arttext&pid=s0034-77442014000600001)


Ramirez, A. & ***P.E., Gutiérrez-Fonseca***. 2014. Functional feeding groups of aquatic insect families in Latin America. Revista de Biológia Tropical. 62(Suppl2):155-167. [PDF](https://www.scielo.sa.cr/scielo.php?pid=S0034-77442014000600011&script=sci_arttext)


***Gutiérrez-Fonseca, P.E.***, & C.M. Lorion. 2014. Application of the BMWP-Costa Rica biotic index in aquatic biomonitoring: sensitivity to collection method and sampling intensity. Revista de Biológia Tropical. 62(Suppl2): 275-289. [PDF](https://www.scielo.sa.cr/scielo.php?pid=S0034-77442014000600018&script=sci_arttext&tlng=en)
<br>
<br>

#### __2013__

***Gutiérrez-Fonseca, P.E.***, & L., Ortiz-Rivas. 2013. Substrate preferences for attaching gumfoot lines in Latrodectus geometricus (Aranae: Theridiidae). Entomological News. 123123(5): 371-379. [PDF](https://bioone.org/journals/entomological-news/volume-123/issue-5/021.123.0508/Substrate-Preferences-for-Attaching-Gumfoot-Lines-in-Latrodectus-geometricus-Araneae/10.3157/021.123.0508.short)


***Gutiérrez-Fonseca, P.E.***, K.G. Rosas & A. Ramirez. 2013. Aquatic insects of Puerto Rico: a list of families. Dugesiana. (20)2: 215-219. [PDF](https://www.researchgate.net/publication/261913585_Aquatic_insects_of_Puerto_Rico_a_list_of_families)

***Gutiérrez-Fonseca, P.E.***, A. Ramirez, G. Umaña & M. Springer. 2013. Macroinvertebrados del agua dulce de la Isla del Coco, Costa Rica: primer listado y un analisis comparativo con otras islas del Pacifico Tropical Oriental. Revista de Biologia Tropical. 61(2):257-268. [PDF](https://www.scielo.sa.cr/pdf/rbt/v61n2/a14v61n2)

Ramirez, A. & ***P.E., Gutiérrez-Fonseca***. 2013. The larvae of Heteragrion majus Selys and H. atrolineatum Donnelly, with a key to known species from Costa Rica (Odonata: Megapodagrionidae). Zootaxa 3609(1): 096-100. [PDF](https://www.mapress.com/zootaxa/2013/f/z03609p100f.pdf)
<br>
<br>

#### __2011__

Ramirez, A., Altamiranda-Saavedra M., ***P.E., Gutiérrez-Fonseca*** & M. Springer. 2011. The Neotropical damselfly genus Cora: new larval descriptions and a comparative analysis of known species (Zygoptera: Polythoridae). International Journal of Odonatology. 14(3): 249-256. [PDF](https://www.tandfonline.com/doi/abs/10.1080/13887890.2011.616992)

***Gutiérrez-Fonseca, P.E.***, & M. Springer. 2011. Description of the final instar nymphs of seven species from Anacroneuria Klapalek (Plecoptera: Perlidae) in Costa Rica, and first record for an additional genus in Central America. Zootaxa 2965: 16-38. [PDF](https://www.researchgate.net/publication/259034499_Description_of_the_final_instar_nymphs_of_seven_species_from_Anacroneuria_Klapalek_Plecoptera_Perlidae_in_Costa_Rica_and_first_record_for_an_additional_genus_in_Central_America)
<br>
<br>

#### __2010__

***Gutiérrez-Fonseca, P.E.***. 2010. Plecoptera. Revista de Biológia Tropical. 58(Suppl. 4): 139-148. [PDF](https://www.scielo.sa.cr/scielo.php?pid=S0034-77442010000800006&script=sci_arttext&tlng=en) 

López, L.I., ***Gutiérrez-Fonseca, P.E.***, & J.M. Mora. 2010. Macrofauna Acuatica de la Quebrada Santa Ines, Subcuenca del Rio Yeguare, Honduras. Ceiba 51:17-28. [PDF](https://s3.amazonaws.com/academia.edu.documents/32831055/Lopez_et_al_macrofauna_Santa_Ines.pdf?response-content-disposition=inline%3B%20filename%3DMacroinvertebrados_de_Santa_Ines_Hondura.pdf&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=ASIATUSBJ6BAI337CXXM%2F20200330%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20200330T131928Z&X-Amz-Expires=3600&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEPT%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCXVzLWVhc3QtMSJHMEUCIFZq1%2BQC%2FzMZvJ%2ByJMOwNJLEWQQ72iNFBkbr3HWNCjEEAiEAynPLNjbvUf2qOrC%2BcwKfTkP5M5e5ahbxKLkp6Inn6TgqvQMI7f%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARAAGgwyNTAzMTg4MTEyMDAiDFe0EInn5fVTk7SkeiqRA0Uds8DPcGBLsfpfk1H8a2L0OP1Kj1VpKQ49ZCzaWcvsSyTCzT85x5m1PaV6o7Z5tC%2Bj3%2BCaUdgnYmLe%2BvzWHx%2FQmXmKyCF57DEgLiAULFhLmapFjMs6RuyP2xXc%2BuFCtnmT1ZCTcVTqheyzRmJi89gYZW1eQ%2BciDqnwLwAZflOA28KDQJLiyyl1h3XlmeZOhI0xMb50Podc%2FOSSZcorJ2uClLAtdTwDaQQcw1h4rgRhviEvP8yAmofBfEUyLn76Zqei8amretHlGvnD9XolHXSEOm9i6Dze1uTycxEH0G0ASRj6n3evHBI5agLHHhBD1t%2FqS5PM4FDDQpaI3%2F%2BvMwKrqLaS6w9MTt5OzBb7KjJA5C6YCtt81%2BpAZj%2BWqJjmhwXFWraSEOQY%2B9Bz6NwO0ElaF6a9vy%2FgtYa14K3cJMXdMevCfypiYFnhHu34mIRWoADDxI7pWa503oiBwD2w%2B7%2FB0eMNyDwzHhPr9Qy9tAzUYtvbSUHtb3kDmpFWHXJGKO5TLgsZAHiY81VpmAEuOH09MLq4h%2FQFOusBUokn9%2Bw4KGTNvQbQUFkcIU35%2BUSSnhoOnLg5Kiyz1%2BJmQXq6vf8Hb2DQN0j0nlA46AzFVzW2PSj3sam6FQPlvHeUmd%2BZj4lBtHTvblMwevCjczGGE5YysddYjMSzBvZs2odntZfJEMyN4Qr7vdS0S%2FFAnxt7KP2Dc2PhMzDCQTdv5nwrx3uHKf1yzDSzDhprVzesnuPShfLD%2FLHNzWSo%2F13YVcsbhfIsoWfzSUCWW8sM%2BQUhOoxbz4KRVEHtY2HYAODqSLbbyuGbk1an%2BPOtEfDBzOMYsx8%2FxOSwCg3KXt2uPJCgVwp6PbG1Zw%3D%3D&X-Amz-SignedHeaders=host&X-Amz-Signature=2ada0e87ee983dd91888d6d440c3acf68f1dde977bcc0d9c81c8abfeb8613e57)
<br>
<br>
<br>
<br>