---
title: "ANOSIM, PERMANOVA, SIMPER, Indicator Value"
author: 
- "Pablo E. Guti&eacute;rrez-Fonseca"
- "`r format(Sys.time(), '%d %B, %Y')`"
layout: default
permalink: /pages/Lectures/Introduction to R/
output: html_document
---
<br/>
<br/>

#### **Step 1**
Load libraries.<br>
_Cargar las librerias que necesitas._
```{r, warning=FALSE,message=FALSE}
libraries <- c("vegan", "ggplot2", "dplyr", "indicspecies", "labdsv", "MASS",
"labdsv", "cluster")
lapply(libraries, require, character.only = TRUE)
```

<br/>

#### **Step 2**
Data<br>
_Cargar los datos._
```{r, echo=FALSE, results='hide'}
laselva_full  <- read.csv("C:/Users/pgutierr/OneDrive - University of Vermont/Curriculum/19_ Personal webpage/TropicalFreshwaterEcology/_pages/Lectures/data/nMDS_laSelva.csv")
head(laselva_full)

```

<br/>

#### **Step 3** 
_Seleccionar la matrix de especies._
```{r, results='hide'}
laselva_sp <- dplyr::select(laselva_full, Baetid:Collemb)
str(laselva_sp)
ncol(laselva_sp)
nrow(laselva_sp)

```

<br/>

## ANOSIM, PERMANOVA, SIMPER, Indicator Value

### Analysis of Similitude
```{r}
laselva.dist <- vegdist(laselva_sp, method="bray")
laselva.anosim <- anosim(laselva.dist, laselva_full$month)
summary(laselva.anosim)
plot(laselva.anosim)
```


```{r}
dis_well <- betadisper(laselva.dist, laselva_full$month)
permutest(dis_well)

well.HSD <- TukeyHSD(dis_well)
well.HSD 

par(mfrow=c(1,2))
plot(well.HSD, las=1)
plot(dis_well, las=1)
```



### PERMANOVA

```{r}

permanova <- adonis(laselva_sp ~ laselva_full$month, data = laselva_full, permutations = 999, method="bray")
summary(permanova)

```



